version: 1.1.{build}
os: Visual Studio 2017
skip_tags: true
configuration: Release

install:
  - cmd: git submodule update --init --recursive

before_build:
  - ps: .\scripts\set-version.ps1
  - cmd: dotnet --info
  - cmd: dotnet restore --verbosity n

build_script:
  - cmd: dotnet build -c Release ExifLibrary\

after_test:
  - cmd: dotnet pack -c Release ExifLibrary\

artifacts:
- path: 'ExifLibrary\bin\Release\*.nupkg'
  name: nugetPackages

deploy:
- provider: NuGet
  api_key:
    secure: 7nX5a7V6wWbtPSJ6bQSU9BRZwJEdn70w0Ydlf5fuk44Gjk9BVgxnYK6u8MNzT2yA
  skip_symbols: true
  artifact: /.*\.nupkg/
  on:
    branch: master
    appveyor_repo_tag: true